apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ kube_logstash_name }}
  labels: {{ kube_logstash_labels | to_nice_json }}
spec:
  template:
    metadata:
      labels: {{ kube_logstash_labels | to_nice_json }}
    spec:
      containers:
      - name: kube-logstash
        image: {{ kube_logstash_image_registry }}{% if  kube_logstash_image_tag is defined and kube_logstash_image_tag is not none %}:{{ kube_logstash_image_tag}}{% endif %}

        resources:
{% if kube_logstash_container_limits is defined %}
          limits: {{kube_logstash_container_limits | to_nice_json}}
{% endif %}

{% if kube_logstash_container_command is defined %}
        command: {{ kube_logstash_container_command | to_nice_json}}
{% endif %}

{% if kube_logstash_container_args is defined %}
        args: {{ kube_logstash_container_args | to_nice_json}}
{% endif %}


{% if kube_logstash_container_volumeMounts is defined %}
        volumeMounts: {{ kube_logstash_container_volumeMounts | to_nice_json}}
{% endif %}

{% if kube_logstash_volumes is defined %}
      volumes: {{ kube_logstash_volumes | to_nice_json }}
{% endif %}
