---
apiVersion: v1
kind: Secret
metadata:
  name: kube-logstash-conf
type: Opaque
data:
{% if kube_logstash_conffiles is defined %}
{% for file in kube_logstash_conffiles %}
  "{{file|basename}}": "{{lookup('file', file) |b64encode}}"

{% endfor %}
{% endif %}
